require('dotenv').config();
const{Client,GatewayIntentBits,SlashCommandBuilder,REST,Routes,EmbedBuilder,ActionRowBuilder,ButtonBuilder,ButtonStyle,ModalBuilder,TextInputBuilder,TextInputStyle}=require('discord.js');
const client=new Client({intents:[GatewayIntentBits.Guilds]});
const API=process.env.API_BASE_URL||'http://localhost:5000';
const GUILD_ID=process.env.GUILD_ID;
const CH_DASH=process.env.CHANNEL_DEADLINE_DASHBOARD;
const CH_ALERT=process.env.CHANNEL_DEADLINE_ALERTS;
const PCOL={critical:0xed4245,high:0xfaa61a,medium:0x5865f2,low:0x57f287};
const PE={critical:'🔴',high:'🟠',medium:'🔵',low:'🟢'};
const SE={pending:'⏳','in-progress':'⚡',completed:'✅'};
const TE={closing:'🏠','loan-docs':'📄',inspection:'🔍',title:'📋',compliance:'⚖️',other:'📌'};
async function api(path,method='GET',body=null){const opts={method,headers:{'Content-Type':'application/json'}};if(body)opts.body=JSON.stringify(body);const r=await fetch(API+path,opts);return r.json();}
function formatDue(d){const now=new Date(),due=new Date(d),days=Math.ceil((due-now)/86400000);if(days<0)return'⚠️ OVERDUE '+Math.abs(days)+'d';if(days===0)return'🔥 Due TODAY';if(days===1)return'⏰ Due tomorrow';return'📅 '+due.toLocaleDateString('en-US',{month:'short',day:'numeric',year:'numeric'});}
function buildEmbed(d){return new EmbedBuilder().setColor(PCOL[d.priority]||0x2d3150).setTitle((PE[d.priority]||'')+' '+d.title).addFields({name:'Priority',value:d.priority.toUpperCase(),inline:true},{name:'Team',value:d.team,inline:true},{name:'Status',value:(SE[d.status]||'⏳')+' '+d.status,inline:true},{name:'Type',value:(TE[d.type]||'📌')+' '+(d.type||'N/A'),inline:true},{name:'Due',value:formatDue(d.dueDate),inline:true},...(d.notes?[{name:'Notes',value:d.notes}]:[])).setFooter({text:'ID: '+d.id}).setTimestamp();}
function buildRow(id,status){return new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId('complete_'+id).setLabel('✅ Complete').setStyle(ButtonStyle.Success).setDisabled(status==='completed'),new ButtonBuilder().setCustomId('inprogress_'+id).setLabel('⚡ In Progress').setStyle(ButtonStyle.Primary).setDisabled(status==='in-progress'),new ButtonBuilder().setCustomId('delete_'+id).setLabel('🗑️ Delete').setStyle(ButtonStyle.Danger));}
const cmds=[new SlashCommandBuilder().setName('deadline').setDescription('Manage BHAT transaction deadlines').addSubcommand(s=>s.setName('add').setDescription('Add a new deadline')).addSubcommand(s=>s.setName('list').setDescription('View open deadlines').addStringOption(o=>o.setName('team').setDescription('Filter by team').addChoices({name:'Frontend TC',value:'Frontend TC'},{name:'Backend TC',value:'Backend TC'})).addStringOption(o=>o.setName('priority').setDescription('Filter by priority').addChoices({name:'Critical',value:'critical'},{name:'High',value:'high'},{name:'Medium',value:'medium'},{name:'Low',value:'low'}))).addSubcommand(s=>s.setName('today').setDescription('Deadlines due today or overdue')).addSubcommand(s=>s.setName('stats').setDescription('Deadline statistics')).toJSON()];
client.once('ready',async()=>{console.log(client.user.tag+' online');const rest=new REST({version:'10'}).setToken(process.env.DISCORD_BOT_TOKEN);await rest.put(Routes.applicationGuildCommands(client.user.id,GUILD_ID),{body:cmds});console.log('Slash commands registered');setInterval(alertCheck,30*60*1000);alertCheck();});
client.on('interactionCreate',async interaction=>{
  if(interaction.isChatInputCommand()&&interaction.commandName==='deadline'){
    const sub=interaction.options.getSubcommand();
    if(sub==='add'){const modal=new ModalBuilder().setCustomId('modal_add').setTitle('📋 New Deadline');modal.addComponents(new ActionRowBuilder().addComponents(new TextInputBuilder().setCustomId('title').setLabel('Property / Title').setPlaceholder('456 Main St — Closing').setStyle(TextInputStyle.Short).setRequired(true)),new ActionRowBuilder().addComponents(new TextInputBuilder().setCustomId('dueDate').setLabel('Due Date (MM/DD/YYYY HH:MM)').setPlaceholder('05/28/2026 17:00').setStyle(TextInputStyle.Short).setRequired(true)),new ActionRowBuilder().addComponents(new TextInputBuilder().setCustomId('priority').setLabel('Priority: critical/high/medium/low').setValue('high').setStyle(TextInputStyle.Short).setRequired(true)),new ActionRowBuilder().addComponents(new TextInputBuilder().setCustomId('team').setLabel('Team: Frontend TC / Backend TC').setValue('Frontend TC').setStyle(TextInputStyle.Short).setRequired(true)),new ActionRowBuilder().addComponents(new TextInputBuilder().setCustomId('notes').setLabel('Notes (optional)').setStyle(TextInputStyle.Paragraph).setRequired(false)));return interaction.showModal(modal);}
    if(sub==='list'){await interaction.deferReply();let dl=await api('/api/deadlines');dl=dl.filter(d=>d.status!=='completed');const tf=interaction.options.getString('team'),pf=interaction.options.getString('priority');if(tf)dl=dl.filter(d=>d.team===tf);if(pf)dl=dl.filter(d=>d.priority===pf);dl.sort((a,b)=>({critical:0,high:1,medium:2,low:3}[a.priority]-{critical:0,high:1,medium:2,low:3}[b.priority]||new Date(a.dueDate)-new Date(b.dueDate)));if(!dl.length)return interaction.editReply('✅ No open deadlines.');await interaction.editReply('📋 **'+dl.length+' open deadline(s)**'+(tf?' — '+tf:''));for(const d of dl.slice(0,8))await interaction.followUp({embeds:[buildEmbed(d)],components:[buildRow(d.id,d.status)]});}
    if(sub==='today'){await interaction.deferReply();const all=await api('/api/deadlines'),now=new Date();const urgent=all.filter(d=>d.status!=='completed'&&new Date(d.dueDate)<=new Date(now.getTime()+86400000));if(!urgent.length)return interaction.editReply('✅ Nothing due in 24h.');await interaction.editReply('🚨 **'+urgent.length+' deadline(s) need attention:**');for(const d of urgent)await interaction.followUp({embeds:[buildEmbed(d)],components:[buildRow(d.id,d.status)]});}
    if(sub==='stats'){await interaction.deferReply();const all=await api('/api/deadlines'),open=all.filter(d=>d.status!=='completed'),now=new Date();const embed=new EmbedBuilder().setColor(0x5865f2).setTitle('📊 BHAT Deadline Stats').setDescription('**'+open.length+'** open  •  **'+(all.length-open.length)+'** completed').addFields({name:'🔴 Critical',value:String(open.filter(d=>d.priority==='critical').length),inline:true},{name:'🟠 High',value:String(open.filter(d=>d.priority==='high').length),inline:true},{name:'🔵 Medium',value:String(open.filter(d=>d.priority==='medium').length),inline:true},{name:'🟢 Low',value:String(open.filter(d=>d.priority==='low').length),inline:true},{name:'⚠️ Overdue',value:String(open.filter(d=>new Date(d.dueDate)<now).length),inline:true},{name:'👥 Frontend TC',value:String(open.filter(d=>d.team==='Frontend TC').length),inline:true},{name:'🔧 Backend TC',value:String(open.filter(d=>d.team==='Backend TC').length),inline:true}).setTimestamp();return interaction.editReply({embeds:[embed]});}
  }
  if(interaction.isModalSubmit()&&interaction.customId==='modal_add'){await interaction.deferReply({ephemeral:true});const title=interaction.fields.getTextInputValue('title'),dueDateRaw=interaction.fields.getTextInputValue('dueDate'),priority=interaction.fields.getTextInputValue('priority').toLowerCase().trim(),team=interaction.fields.getTextInputValue('team').trim(),notes=interaction.fields.getTextInputValue('notes')||'',dueDate=new Date(dueDateRaw);if(isNaN(dueDate))return interaction.editReply({content:'❌ Invalid date. Use MM/DD/YYYY HH:MM'});if(!['critical','high','medium','low'].includes(priority))return interaction.editReply({content:'❌ Priority: critical, high, medium, or low'});const created=await api('/api/deadlines','POST',{title,dueDate:dueDate.toISOString(),priority,team,notes,status:'pending'});await interaction.editReply({content:'✅ Deadline created!'});const ch=client.channels.cache.get(CH_DASH);if(ch)await ch.send({content:'📋 New deadline added by <@'+interaction.user.id+'>',embeds:[buildEmbed(created)],components:[buildRow(created.id,created.status)]});}
  if(interaction.isButton()){const[action,id]=interaction.customId.split('_');await interaction.deferUpdate();if(action==='complete'){const u=await api('/api/deadlines/'+id,'PUT',{status:'completed'});await interaction.editReply({embeds:[buildEmbed(u)],components:[buildRow(u.id,u.status)]});await interaction.followUp({content:'✅ **'+u.title+'** marked complete by <@'+interaction.user.id+'>'});}if(action==='inprogress'){const u=await api('/api/deadlines/'+id,'PUT',{status:'in-progress'});await interaction.editReply({embeds:[buildEmbed(u)],components:[buildRow(u.id,u.status)]});}if(action==='delete'){await api('/api/deadlines/'+id,'DELETE');await interaction.editReply({content:'🗑️ Deleted by <@'+interaction.user.id+'>',embeds:[],components:[]});}}
});
async function alertCheck(){const ch=client.channels.cache.get(CH_ALERT);if(!ch)return;const all=await api('/api/deadlines').catch(()=>[]),now=new Date();const urgent=all.filter(d=>d.status!=='completed'&&new Date(d.dueDate)<=new Date(now.getTime()+86400000));if(!urgent.length)return;const embed=new EmbedBuilder().setColor(0xed4245).setTitle('🚨 Deadline Alert — Action Needed').addFields(urgent.map(d=>({name:(PE[d.priority]||'')+' '+d.title,value:formatDue(d.dueDate)+' • '+d.team+' • '+d.status}))).setTimestamp();await ch.send({content:'@here',embeds:[embed]});}
client.login(process.env.DISCORD_BOT_TOKEN);
